import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/myui/Header";
import { Platypi } from "next/font/google";
import Footer from "@/components/myui/Footer";
import SmoothScroll from "@/smooth";
import Fixmessage from "@/components/myui/Fixmessage";
import Cursor from "../Cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const rockSalt = Platypi({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html lang="en" className="scroll-smooth">
      <SmoothScroll>
        <body
          className={`${rockSalt.className} min-h-full flex flex-col overflow-x-hidden`}
        >
          <div className="">
            <Cursor />
            <Header />
          </div>
          {children}
          <div className="">
            <div className=" z-40">
              <Fixmessage />
            </div>

            {/* Footer ko clear strong stacking stack layer (z-50) di taaki baqi saare elements iske neeche chup skein */}
            <div className="relative z-50 bg-white dark:bg-zinc-950">
              <Footer />
            </div>
          </div>
        </body>
      </SmoothScroll>
    </html>
  );
}
